Dockerfile.yalm
FROM nginx: 1.25.3
COPY nginx.conf /etc/nginx/nginx.conf
RUN adduser --disabled-password --gecos '' nginxuser && \
    chown -R nginxuser:nginxuser /var/cache/nginx /var/run /var/log/nginx /etc/nginx && \
    touch /var/run/nginx.pid && \
    chown -R nginxuser:nginxuser /var/run/nginx.pid /var/log/nginx
USER nginxuser
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]

