apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
type: Opaque
data:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
  database: {{ .Values.postgres.database }}